# Generated by Django 3.2.4 on 2021-12-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='image',
        ),
    ]
